{
    "name": "tarh_konyvel",
    "version": "1.0",
    "depends": ["base","crm"],
    "author": "VígJAni",
    "category": "category",
    "description": """
    This module provide : Társasházak könyvelése, adatbevitel, lekérdezés
    """,
    "init_xml": [],
    'update_xml': [],
    'demo_xml': [],
    'data':['lekerdez_lakoegy.xml',
            'lekerdez_lakoegy2.xml',
            'reports.xml',
            'tarh_konyvel_view2.xml',
            'lekerdez.xml',
            'tarh_konyvel_view.xml',
            'tarh_kozoskt.xml',
            'tarh_kozoskt_lekerdezes.xml',
            'tarh_rendkivuli_lekerdez.xml',
            'tarh_kinnlevoseg_view.xml',
            'tarh_bej_szamlak_view.xml',
            'kiserlet.xml',
            'portal_user_view.xml',
            'tarh_tartozok.xml',
            'layouts.xml',
            'tarh_lako_eves_view.xml',
            'tarh_lako_eves_nyomtat.xml',
            'tarh_epites_view.xml',
            'tarh_epites_nyomtat.xml',
            'tarh_egyszeribeir_view.xml',
            'tarh_havijelentes_view.xml',
            ],
    'installable': True,
  
}
